[build.environment]
  TZ = "America/Chicago"

[[redirects]]
  from = "http://whenwillweherd.com/*"
  to = "https://whenwillweherd.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.whenwillweherd.com/*"
  to = "https://whenwillweherd.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.whenwillweherd.com/*"
  to = "https://whenwillweherd.com/:splat"
  status = 301
  force = true
